### ISSUE TITLE
All the screenshot links are broken in readme.md.

### ISSUE THREAD

**Issue by VesterDe** [proteusthemes/mailchimp-widget#1]
See title.

**Comment by primozcigler** [comment]
Thanks for pointing out. That's because we only maintain `readme.txt` and create `readme.md` with the grunt task: https://github.com/proteusthemes/mailchimp-widget/blob/master/Gruntfile.js#L80-L86

They work in the official repo: https://wordpress.org/plugins/proteusthemes-mailchimp-widget/

If you know the fix, let me know.
